fastq-coverage: Rewritten in Perl

diff --git a/fastq-coverage b/fastq-coverage
--- a/fastq-coverage
+++ b/fastq-coverage
@@ -1,87 +1,125 @@
-#! /bin/bash
+#! /usr/bin/env perl
 
-set -e
-set -o pipefail
+use strict;
+use feature 'postderef';
+use warnings FATAL => 'all';
+no warnings "experimental::postderef";
+#use Carp::Always;
 
-export LC_ALL=C
+# use FindBin;
+# use lib "$FindBin::Bin";
+# use Xyzzy;
 
-opt_p=2
-opt_g=5Mbps
+use constant { TRUE => 1, FALSE => 0 };
 
-_usage=
-
-_usage+="Usage: $0 [options] 1.fastq.gz 2.fq ...\n"
-_usage+="-g SIZE - genome size [$opt_g]\n"
-_usage+="-h - this message\n"
-_usage+="-p NUM - precision of output [$opt_p]\n"
-
-function usage {
-    echo -e -n "$_usage" 1>&2
-    exit "$@"
-}    
-
-# v-- add this if inside a function
-# local OPTIND opt_h opt_o
-
-while getopts 'g:hp:' opt ; do
-    case "$opt" in
-	g) opt_g="$OPTARG" ;;
-	h) opt_h=1 ;;
-	p) opt_p="$OPTARG" ;;
-	\?) usage 1 ;;
-	*) echo 1>&2 "Can't happen" ; exit 1 ;;
-    esac
-done
-shift $((OPTIND-1))
-
-if [ "$opt_h" ] ; then
-    usage
-fi
+# 'wide character' warning.
+binmode(STDIN, ":utf8");
+binmode(STDOUT, ":utf8");
 
 # ------------------------------------------------------------------------
 
-num="$(echo "$opt_g" | sed -e 's/^\([0-9][0-9,]*\).*/\1/')"
-# if [ "$num" = "$opt_g" ] ; then
-#     echo 1>&2 "Ill-formed genome size: $opt_g"
-#     exit 1
-# fi
-num="$(echo $num | sed -e 's/,//g')"
+use File::Basename;
+use Getopt::Std;
 
-foo="$(echo "$opt_g" | sed -e 's/^[0-9][0-9,]*//' -e 's/[bB][pP][sS]$//')"
+our $opt_h;
+our $opt_g = "5Mbps";
+our $opt_p = 2;
 
-if [ "$foo" = "" ] ; then
-    factor=1
-elif [ "$foo" = "k" -o "$foo" = "K" ] ; then
-    factor=1000
-elif [ "$foo" = "m" -o "$foo" = "M" ] ; then
-    factor=1000000
-elif [ "$foo" = "g" -o "$foo" = "G" ] ; then
-    factor=1000000000
-else
-    echo 1>&2 "Ill-formed genome size: $opt_g"
-    exit 1
-fi  
+my $usage_str = "";
+my $progname = basename($0);
+$usage_str .= "Usage: $progname [options] reads1.fastq.gz reads2.fq ...\n";
 
-size=$[ $num * $factor ]
+$usage_str .= "-h - print help\n";
+$usage_str .= "-g NUM - genome size [$opt_g]\n";
+$usage_str .= "-g FASTA_FILE - genome to use for size calculation\n";
 
-# ------------------------------------------------------------------------
-
-function count_bases {
-    (
-	for f in "$@" ; do
-	    case X"$f"X in
-		X*.gzX) gzip -cd "$f" ;;
-		*) cat "$f"
-	    esac
-	done
-    ) | fastq2seq | strings-length | profile-reduce + 0
+sub usage {
+  print STDERR $usage_str;
+  exit(@_);
 }
 
-bases=$(count_bases "$@")
+my $stat = getopts('g:hp:');
+if (!$stat) {
+  usage(1);
+}
+if ($opt_h) {
+  usage();
+}
+if (scalar(@ARGV) == 0) {
+  usage(1);
+}
 
 # ------------------------------------------------------------------------
+# Compute genome size
+# ------------------------------------------------------------------------
 
-coverage=$(dc -e "$opt_p k $bases.0 $size.0 / p")
+my $genome_size;
 
-echo $coverage
+if ( -e $opt_g ) {
 
+  my $fh;
+  if ( $opt_g =~ /.gz$/ ) {
+    open($fh, "-|", "gzip -cd $opt_g") || die "Cannot open: <<$opt_g>>,";
+  } else {
+    open($fh, "<", $opt_g) || die "Cannot open: <<$opt_g>>,";
+  }
+  $genome_size = 0;
+  while (<$fh>) {
+    chomp;
+    if (/^>/) {
+      next;
+    } else {
+      $genome_size += length($_);
+    }
+  }
+  close ($fh) || die;
+
+} else {
+
+  ($opt_g =~ /^([0-9.][0-9.,]*)([a-zA-Z]?)/) || die "Ill-formed genome size.";
+  my ($num,$factor) = ($1,lc($2));
+  $num =~ s/,//g;
+
+  if ( $factor eq "" ) {
+    $genome_size = $num;
+  } elsif ($factor eq "k") {
+    $genome_size = $num * 1000;
+  } elsif ($factor eq "m") {
+    $genome_size = $num * 1000000;
+  } elsif ($factor eq "g") {
+    $genome_size = $num * 1000000000;
+  } else {
+    die "Ill-formed genome size.";
+  }
+}
+
+# ------------------------------------------------------------------------
+# Count read bases
+# ------------------------------------------------------------------------
+
+my $bases = 0;
+foreach my $fn ( @ARGV ) {
+  my $fh;
+  if ( $fn =~ /.gz$/ ) {
+    open($fh, "-|", "gzip -cd $fn") || die "Cannot open: <<$fn>>,";
+  } else {
+    open($fh, "<", $fn) || die "Cannot open: <<$fn>>,";
+  }
+  my $i=0;
+  while (<$fh>) {
+    chomp;
+    if ($i == 1) {
+      $bases += length($_);
+    }
+    $i = ($i+1) % 4 ;
+  }
+  close ($fh) || die;
+}
+
+# ------------------------------------------------------------------------
+# Print results
+# ------------------------------------------------------------------------
+
+my $coverage = (1.0*$bases) / (1.0*$genome_size);
+
+printf "%.*f\n", $opt_p, $coverage;
